### ISSUE TITLE
Dudas varias

### ISSUE THREAD

**Issue by 29antonioac** [iblancasa/PythonEO#3]
A seguir dando la lata, pues. Sólo preguntar por qué usas math.floor para tomar la parte entera cuando randint ya devuelve un entero, y por qué no usar una estructura mutable (una lista) en vez de un string, que es inmutable.

Nos vemos :D

**Comment by iblancasa** [comment]
A math.floor: simplemente copié del ejemplo de LUA, no vi que hacía (soy un petardo, lo sé :worried: )
En cuanto a lo otro... no sabía que un string es inmutable, pero me pasó 3/4 de lo mismo. Resulta que vi que usaba un string y entendí que lo hacía por algún motivo (tengo que decir que cuando me puse a hacerlo no sabía muy bien qué hacia el programa original... así que iba un poco siguiendo lo que hacía sin pararme mucho a ver por qué y tal...) Cuando he hecho el de Julia, he entendido que hacerlo con listas tiene más sentido. Cuando tenga un rato me pongo. Gracias por la sugerencia :neckbeard:

**Comment by iblancasa** [comment]
Ya está hecho. 
He estado mirando para hacerlo con booleanos (a JJ le resultó bien la prueba en Julia), pero son subtipos de enteros... así que ocupan los mismo y tal.
Al comprobar con la función "getsizeof" del módulo "sys", veo que lo siguiente:

``` python
>>> x = 2
>>> sys.getsizeof(x)
28
>>> sys.getsizeof(1)
28
>>> sys.getsizeof("1")
50
>>> sys.getsizeof(True)
28
```

He visto que esto varía en función de la versión del SO y de Python... así que tampoco creo que merezca la pena usar cadenas en vez de caracteres (en este lenguaje)

**Comment by 29antonioac** [comment]
Otra cosilla. En bitflip no incluyes en el benchmark la generación de un individuo aleatorio, pero en onemax sí que lo haces... ¿En qué quedamos? :ghost: Es para hacerlo igual en [RubyEO](https://github.com/analca3/RubyEO)

**Comment by iblancasa** [comment]
@analca3 está tal cual lo tiene @JJ en [LunEO](https://github.com/JJ/LunEO)

**Comment by JJ** [comment]
En OneMax tiene que ser un individuo diferente cada vez. En bitblip basta con que uses el anterior...

**Comment by 29antonioac** [comment]
No tiene sentido de otra forma, sí.

2015-11-22 18:52 GMT+01:00 Juan Julián Merelo Guervós <
notifications@github.com>:

> En OneMax tiene que ser un individuo diferente cada vez. En bitblip basta
> con que uses el anterior...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iblancasa/PythonEO/issues/3#issuecomment-158781178.

## 

Antonio Álvarez Caballero
