### ISSUE TITLE
Pypy or Python

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/PythonEO#8]

**Comment by iblancasa** [comment]
Pypy:

onemax
python-Onemax, 16, 6.7700000000000005
python-Onemax, 32, 10.609998999999998
python-Onemax, 64, 18.746665
python-Onemax, 128, 32.83999700000001
python-Onemax, 256, 85.009991
python-Onemax, 512, 166.709983
python-Onemax, 1024, 379.22329600000006
python-Onemax, 2048, 685.8799309999999
python-Onemax, 4096, 1280.523205

bitflip
python-BitFlip, 16, 2.4499999999999997
python-BitFlip, 32, 2.4933329999999994
python-BitFlip, 64, 2.546666
python-BitFlip, 128, 2.466667000000001
python-BitFlip, 256, 2.636666
python-BitFlip, 512, 2.4133329999999997
python-BitFlip, 1024, 2.3133320000000026
python-BitFlip, 2048, 2.4499999999999957
python-BitFlip, 4096, 2.490000000000002
python-BitFlip, 8192, 2.506667
python-BitFlip, 16384, 2.999998999999999
python-BitFlip, 32768, 2.8733320000000013

xover
python-Xover, 16, 4.93
python-Xover, 32, 4.706666000000001
python-Xover, 64, 4.743331999999999
python-Xover, 128, 4.800001
python-Xover, 256, 5.206666000000002
python-Xover, 512, 5.683333000000001
python-Xover, 1024, 6.8166660000000014

**Comment by iblancasa** [comment]
Python:

onemax:
python-Onemax, 16, 1.578328
python-Onemax, 32, 2.005355
python-Onemax, 64, 4.391267000000001
python-Onemax, 128, 4.557805
python-Onemax, 256, 12.458427000000002
python-Onemax, 512, 15.353807000000003
python-Onemax, 1024, 37.71549999999999
python-Onemax, 2048, 80.90450399999999
python-Onemax, 4096, 

bitflip:
python-BitFlip, 16, 0.42683099999999996
python-BitFlip, 32, 0.405336
python-BitFlip, 64, 0.405096
python-BitFlip, 128, 0.463136
python-BitFlip, 256, 0.40273500000000007
python-BitFlip, 512, 0.43586100000000005
python-BitFlip, 1024, 0.431829
python-BitFlip, 2048, 0.4619019999999998
python-BitFlip, 4096, 0.4509920000000003
python-BitFlip, 8192, 0.4355439999999997
python-BitFlip, 16384, 0.44179299999999966
python-BitFlip, 32768, 0.47850000000000037

xover
python-Xover, 16, 1.0201689999999999
python-Xover, 32, 1.036853
python-Xover, 64, 1.0865939999999998
python-Xover, 128, 1.2269929999999998
python-Xover, 256, 1.5154039999999993
python-Xover, 512, 2.120695999999999
python-Xover, 1024, 3.5777839999999994

**Comment by iblancasa** [comment]
@JJ los resultados empeoran.
Arriba he usado Pypy.
Abajo he usado Python 3.5

**Comment by JJ** [comment]
jolines...

**Comment by JJ** [comment]
¿Será más rápido que Python 2?

**Comment by iblancasa** [comment]
Sí, lo probé
